codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "99...100"

  status:
    project:
      default:
        target: 99%
        threshold: 1%
        base: auto
        flags:
          - unit
        paths:
          - "ovmobilebench"
          - "helpers"
        if_not_found: failure
        if_ci_failed: error
        informational: false
        only_pulls: false

    patch:
      default:
        target: 99%
        threshold: 1%
        base: auto
        if_not_found: failure
        if_ci_failed: error
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
  branches:
    - "main"
    - "develop"

flags:
  unit:
    paths:
      - ovmobilebench/
      - helpers/
    carryforward: false

ignore:
  - "tests/**/*"
  - "experiments/**/*"
  - "docs/**/*"
  - "examples/**/*"
  - "setup.py"
  - "**/__init__.py"
  - "**/test_*.py"
  - "**/*_test.py"
  - "**/__pycache__"
  - "**/*.pyc"
